kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${env.NAME}
  namespace: ${env.NS}
spec:
  selector:
    matchLabels:
      app: ${env.NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${env.NAME}
    spec:
      containers:
      - name: ${env.NAME}
        image: $DOCKERIMG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${env.NAME}
  namespace: ${env.NS}
spec:
  selector:
    app: ${env.NAME}
  type: NodePort
  ports:
    - name: ${env.NAME}-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8080