apiVersion: v1
kind: Namespace
metadata:
  name: $k8sNamespace
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: $Name
  namespace: $k8sNamespace
  labels:
    app: $Name
spec:
  selector:
    matchLabels:
      app: $Name
  template:
    metadata:
      labels:
        app: $Name
    spec:
      containers:
      - name: $Name
        image: $imageName
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: $Name
  namespace: $k8sNamespace
  labels:
    app: $Name
spec:
  selector:
    app: $Name
  type: ClusterIP
  ports:
    - name: $Name-port
      protocol: TCP
      port: 80
      targetPort: 80
